Port=510
IP=172.16.30.101
Port1=Yes
Port1Speed=19200
Port1Parity=None
Port1Stop=1
Port2=No
Port2Speed=19200
Port2Parity=None
Port2Stop=1
Port3=No
Port3Speed=19200
Port3Parity=None
Port3Stop=1
Port4=No
Port4Speed=19200
Port4Parity=None
Port4Stop=1
Port5=No
Port5Speed=19200
Port5Parity=None
Port5Stop=1
